### PR TITLE
Use Numbering so Sections are easier to follow

### PR DESCRIPTION
**Pull request by thadguidry**

### CODE REVIEW

**Comment by justelad** [comment]
i concur with @homotopycolimit, scratch the original change and just add `:numbered:` on the line after `toctree` - sphinx will do the rest.

cheers

**Comment by thadguidry** [comment]
The reStructuredText docs actually say to use ...
`In addition, the auto-enumerator, "#", may be used to automatically enumerate a list. Auto-enumerated lists may begin with explicit enumeration, which sets the sequence. Fully auto-enumerated lists use arabic numerals and begin with 1. (Auto-enumerated lists are new in Docutils 0.3.8.)` - http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#enumerated-lists

**Comment by justelad** [comment]
this is not a classic enumerated list but needs to enumerate across different pages and according to the toctree set depth. i'm not sure how you intend to use the aforementioned enumerated lists to auto-number across different files.
i think that in this case the sphinx docs wins since we need to enumerate over a sphinx feature (rst does not know `toctree`

**Comment by justelad** [comment]
pushed the one-liner straight to `master`, closing this due to inactivity. thanks for the improvement @thadguidry!

**Comment by thadguidry** [comment]
@justelad no problem !

**Pull request closed without merging**
